server: 
  port: 8761
spring: 
  application: 
    name: netflix-eureka-naming-server
eureka: 
  instance: 
    hostname: localhost
  client: 
    register-with-eureka: false
    fetch-registry: false
    healthcheck.enabled: true
management:  endpoints:    web:      exposure:        include:        - '*'